def build(bld):
    for name in [
            'astVisitor',
            'astExpose',
            'clangTooling',
            'asttoolingPackage',
            'clangCompiler' ]:
        bld.clasp_source_files.append(bld.path.find_node(name+'.cc'))

        
