#!/bin/bash
# Usage:  $0 <pid> <time>
echo PID $1  time: $2
PID=$1
TIME=${2:-30s}
sudo dtrace -p $1 -x ustackframes=2000 -n "pid$PID::*cxa_throw*:entry / pid == $PID / {@[ustack()] = count();}   tick-$TIME { exit(0); }" -o /tmp/out-throw-$PID.raw.stacks

