
include	$(CANDO_HOME)/makefile.inc

printenv:
	echo CANDO_APP_RESOURCES_LISP_DIR=$(CANDO_APP_RESOURCES_LISP_DIR)


subAll sa sad:
	make subBundle

subBundle sb:
	install -d $(CANDO_APP_RESOURCES_LISP_DIR)/CANDO/patterns
	install -c *.l $(CANDO_APP_RESOURCES_LISP_DIR)/CANDO/patterns

subInstall:
	@echo Install buildDatabase cando-script code, for now do nothing


subClean:
	@echo DO nothing


