PACKAGE= patterns


include	$(CANDO_HOME)/makefile.inc

printenv:
	echo CANDO_APP_RESOURCES_CSC_DIR=$(CANDO_APP_RESOURCES_CSC_DIR)


subAll sa:
	make subBundle

subBundle sb:
	install -d $(CANDO_APP_RESOURCES_CSC_DIR)/CANDO/$(PACKAGE)
	install -c *.l $(CANDO_APP_RESOURCES_CSC_DIR)/CANDO/$(PACKAGE)

subInstall:
	@echo Install $(PACKAGE) cando-script code, for now do nothing


subClean:
	@echo DO nothing


