;;-*- Lisp -*-

(def-test-system test-defsystem-depends-on-1
  :defsystem-depends-on (test-asdf/l-file)
  :default-component-class "l-file:cl-source-file.l"
  :components
  ((:cl-source-file.l "file1" :type "lisp")
   (:cl-source-file "file2" :depends-on ("file1"))
   (:file "test-extension")))

(load-system :test-defsystem-depends-on-1)

(def-test-system test-defsystem-depends-on-2
  :defsystem-depends-on (test-asdf/l-operation)
  :build-operation "l-operation:op"
  :components
  ((:file "file3")))

(assert-equal 0 l-operation:*x*)

(make :test-defsystem-depends-on-2)

(assert-equal 2 l-operation:*x*) ;; perform called twice, on file and on system.

(def-test-system test-defsystem-depends-on-3
  :defsystem-depends-on (test-asdf/l-operation)
  :build-operation "does-not-exist"
  :components ((:file "file3")))

(signals asdf::formatted-system-definition-error (make :test-defsystem-depends-on-3))
