;;; -*- Lisp -*-

;;; test asdf:try-recompiling restart

(defvar *caught-error* nil)
(delete-file-if-exists "try-reloading-dependency.asd")
(with-asdf-cache (:override t)
(handler-bind
    ((error #'(lambda (c)
                (format t "~&Caught error ~s" c)
		(assert (not *caught-error*) () "Déjà vu")
                (setf *caught-error* t)
                (concatenate-files '("try-reloading-dependency.hidden") "try-reloading-dependency.asd")
                (DBG "trlc1 5")
                (multiple-value-bind (name mode) (find-symbol* :retry :asdf)
                  (assert (eq mode :external) () "Mode of ~s was not external" name)
                  (let ((restart (find-restart name c)))
                    (assert restart)
                    (when restart (invoke-restart restart)))))))
  (load-system 'try-reloading-1))
(assert *caught-error*))
