;;; -*- Lisp -*-



;;(trace asdf::source-file-type asdf::source-file-explicit-type)

(progn
 (asdf:load-system 'test-source-file-type-1 :verbose t)
 (assert (symbol-value (read-from-string "test-package::*test-tmp-cl*")))
 (assert
   (equal (mapcar #'pathname-type
                  (mapcar #'asdf:component-pathname (asdf:module-components (asdf:find-system :test-source-file-type-1))))
          '("lisp" "cl")))
 (delete-package :test-package)
 (asdf:load-system 'test-source-file-type-2 :verbose t)
 (assert (symbol-value (read-from-string "test-package::*test-tmp-cl*"))))
