;;-*- Lisp -*-

(load-system 'test-mutual-redefinition-1)
(defun current-system-source-file (x)
  (system-source-file (cdr (gethash x asdf/find-system:*defined-systems*))))

(with-asdf-cache ()
  (DBG "loading test-mutual-redefinition-1")
  (assert-pathname-equal
   (test-source "test-mutual-redefinition-1.asd")
   (current-system-source-file "test-mutual-redefinition-1"))
  (assert-pathname-equal
   (test-source "test-mutual-redefinition-1.asd")
   (current-system-source-file "test-mutual-redefinition-2"))

  (DBG "loading test-mutual-redefinition-2 in the same cache session")
  (load-system 'test-mutual-redefinition-2)
  (assert-pathname-equal
   (test-source "test-mutual-redefinition-1.asd")
   (current-system-source-file "test-mutual-redefinition-1"))
  (assert-pathname-equal
   (test-source "test-mutual-redefinition-1.asd")
   (current-system-source-file "test-mutual-redefinition-2"))

  (with-asdf-cache (:override t)
    (DBG "loading test-mutual-redefinition-2 in a different cache session")
    (load-system 'test-mutual-redefinition-2)
    (assert-pathname-equal
     (test-source "test-mutual-redefinition-2.asd")
     (current-system-source-file "test-mutual-redefinition-1"))
    (assert-pathname-equal
     (test-source "test-mutual-redefinition-2.asd")
     (current-system-source-file "test-mutual-redefinition-2"))))
