(let ((l '(1 2 33 4 5 6)))
  (do* ((cur l (cdr cur))
	(bb (car cur) (car cur)))
      ((null bb) (bformat t "Done\n"))
    (bformat t "cur --> %s\n" cur)
    (bformat t "bb --> %s\n" bb)
    (cond ((progn
	     (bformat t "First cond test - always fails\n")
	     nil)
	   (bformat t "Never reach here\n"))
	  ((eql bb 3) (return)))
    (bformat t "dropped through the bottom of cond\n")
    )
  )

