(defvar cmp:*low-level-trace* t)
(defvar cmp:*debug-compiler* t)
(load-boot :stage1)
(print "About to compile lambdaList-a.lsp")
(compile-file "lambdaList-a.lsp")
(print "About to bcload lambdaList-a.lsp")
(bcload "lambdaList-a.bc")
(bformat t "Result of evaluating (a :y 10) = %s\n" (a :y 10))
(bformat t "Result of evaluating (a) = %s\n" (a))

(bformat t "(foo :allow-other-keys t :y 107 :allow-other-keys nil :w 'hi :x 44) --> %s\n" (foo :allow-other-keys t :y 107 :allow-other-keys nil :w 'hi :x 44))
