def build(bld):
    for name in [
            'gc_interface',
            'boehmGarbageCollection',
            'mpsGarbageCollection',
            'hardErrors',
            'source_info',
            'threadlocal',
            'gc_boot',
            'interrupt',
            'gcFunctions',
            'gctoolsPackage',
            'globals',
            'gcStack',
            'gcalloc',
            'gcweak',
            'memoryManagement']:
        full_name = name+'.cc'
        node = bld.path.find_node(full_name)
        assert node != None, "Could not find %s/%s" % ( bld.path.abspath(), full_name )
        bld.clasp_source_files.append(node)
    gc_name = 'mygc.c'
    node = bld.path.find_node(gc_name)
    assert node != None, "Could not find %s/%s" % ( bld.path.abspath(), full_name )
    bld.clasp_source_files.append(node)

        
