def build(bld):
    for name in [
            'gc_interface',
            'gc_boot',
            'gcFunctions',
            'gctoolsPackage',
            'globals',
            'gcStack',
            'telemetry',
            'gcalloc',
            'gcweak',
            'memoryManagement']:
        bld._source_files.append(bld.path.find_node(name+'.cc'))
    bld._source_files.append(bld.path.find_node('mygc.c'))

        
