def build(bld):
    for name in [
            'sockets',
            'socketsPackage']:
        full_name = name+'.cc'
        node = bld.path.find_node(full_name)
        assert node != None, "Could not find %s/%s" % ( bld.path.abspath(), full_name )
        bld.clasp_source_files.append(node)

        
