#!/bin/bash
 
#PBS -N opt4
#PBS -o out/_opt4.stdout
#PBS -e out/_opt4.error
#PBS -l nodes=1:ppn=1:small_io
#PBS -l mem=200mb
#PBS -l walltime=20:00:00 
#PBS -V

export DIR=/home/other/meister/Development/cando/src/tools/spinProbes 
cd $DIR
/usr/prog/mpi/bin/mpirun -np 1 \
	/home/other/meister/local/bin/pyMPI \
	$DIR/mpiSpectrumFit --outputPrefix out/_opt4\
	--spectrum $DIR/parms/ss4mer.txt --column 2 --createNMer 4 \
	--logMonteCarloStep 4 > $DIR/out/_opt4.log
