(in-package :asdf-user)

(defsystem "code-weight"
  :description "Measure inlining weight"
  :version "0.0.1"
  :author "Christian Schafmeister <chris.schaf@verizon.net>"
  :description "Tool for measuring the code generated by inlining.  Compile-file files with :output-info t and generate .ll files and then pass a list of .ll files to the analyze-code function."
  :licence "LGPL-3.0"
  :depends-on ( :cl-ppcre)
  :serial t
  :components
  ((:file "packages")
   (:file "code-weight")))
