/*
    File: core_globals.h
*/

/*
Copyright (c) 2014, Christian E. Schafmeister
 
CLASP is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.
 
See directory 'clasp/licenses' for full details.
 
The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
/* -^- */

#ifndef globals_H
#define globals_H

#include <clasp/core/foundation.h>

namespace core {

/*! Used in lisp.cc to keep track of new predefined symbols
 */
extern uint __nextPredefinedSymbolIndex;
};

extern "C" {
/*! This stores a pointer to the run-time value vector.
      This is linked to by LLVM Modules generated by COMPILE.
      The LoadTimeValues_O structures are allocated in a memory pool that does not move its contents!!!
    */
extern core::LoadTimeValues_O *globalTaggedRunTimeValues ATTR_WEAK;
};

extern "C" {
#define _LISP _lisp
DLL_PUBLIC extern core::Lisp_sp _lisp;
};

#endif
