
#ifdef SCRAPING
#define LAMBDA(...) LAMBDA_zq1oHBQVhqV9n0CQlhtx_BEGIN (__VA_ARGS__) LAMBDA_zq1oHBQVhqV9n0CQlhtx_END
#define DOCSTRING(...) DOCSTRING_kFF85gTJScPfuWfQ_BEGIN (__VA_ARGS__) DOCSTRING_kFF85gTJScPfuWfQ_END
#define DECLARE(...) DECLARE_baXVYlGg2BHYj1ZCasGHg_BEGIN (__VA_ARGS__) DECLARE_baXVYlGg2BHYj1ZCasGHg_END
#define DEFUN_BEGIN EXPOSE_FUNCTION_kgLQIwkiLOdsLMYsDUj3YAX3wg8_BEGIN
#define DEFUN_END EXPOSE_FUNCTION_kgLQIwkiLOdsLMYsDUj3YAX3wg8_END
#define CL_NAMESPACE NAMESPACE_384fF3FU8FK
#else
#define LAMBDA(...)
#define DOCSTRING(...)
#define DECLARE(...)
#define DEFUN_BEGIN
#define DEFUN_END
#endif
