
#ifdef SCRAPING
#define LAMBDA(...) LAMBDA_zq1oHBQVhqV9n0CQlhtx_BEGIN (__VA_ARGS__) LAMBDA_zq1oHBQVhqV9n0CQlhtx_END
#define DOCSTRING(...) DOCSTRING_kFF85gTJScPfuWfQ_BEGIN (__VA_ARGS__) DOCSTRING_kFF85gTJScPfuWfQ_END
#define DECLARE(...) DECLARE_baXVYlGg2BHYj1ZCasGHg_BEGIN (__VA_ARGS__) DECLARE_baXVYlGg2BHYj1ZCasGHg_END
#define CL_DEFUN() EXPOSE_FUNCTION_kgLQIwkiLOdsLMYsDUj3YAX3wg8
#define CL_NAMESPACE() NAMESPACE_384fF3FU8FK
#else
#define LAMBDA(...)
#define DOCSTRING(...)
#define DECLARE(...)
#define CL_DEFUN()
#define CL_NAMESPACE()
#endif
