
#ifdef SCRAPING
#define BEGIN_TAG BEGIN_TAG_bfc54f90bafadf5
#define END_TAG END_TAG_bfc54f90bafadf5
#define LAMBDA(...) BEGIN_TAG LAMBDA_BEGIN #__VA_ARGS__ END_TAG
#define DOCSTRING(...) BEGIN_TAG DOCSTRING_BEGIN __VA_ARGS__ END_TAG
#define DECLARE(...) BEGIN_TAG DECLARE_BEGIN #__VA_ARGS__ END_TAG
#define CL_DEFUN BEGIN_TAG EXPOSE_FUNCTION __FILE__ __LINE__
#define CL_NAMESPACE BEGIN_TAG NAMESPACE
#else
#define LAMBDA(...)
#define DOCSTRING(...)
#define DECLARE(...)
#define CL_DEFUN
#define CL_NAMESPACE
#endif
