#ifndef virtualMachine_H
#define virtualMachine_H

enum vm_codes {
   vm_ref=0,
   vm_const=1,
   vm_closure=2,
   vm_call=3,
   vm_call_receive_one=4,
   vm_call_receive_fixed=5,
   vm_bind=6,
   vm_set=7,
   vm_make_cell=8,
   vm_cell_ref=9,
   vm_cell_set=10,
   vm_make_closure=11,
   vm_make_uninitialized_closure=12,
   vm_initialize_closure=13,
   vm_return=14,
   vm_bind_required_args=15,
   vm_bind_optional_args=16,
   vm_vaslistify_rest_args=17,
   vm_listify_rest_args=18,
   vm_parse_key_args=19,
   vm_jump_8=20,
   vm_jump_16=21,
   vm_jump_24=22,
   vm_jump_if_8=23,
   vm_jump_if_16=24,
   vm_jump_if_24=25,
   vm_jump_if_supplied_8=26,
   vm_jump_if_supplied_16=27,
   vm_check_arg_count_LE_=28,
   vm_check_arg_count_GE_=29,
   vm_check_arg_count_EQ_=30,
   vm_push_values=31,
   vm_append_values=32,
   vm_pop_values=33,
   vm_mv_call=34,
   vm_mv_call_receive_one=35,
   vm_mv_call_receive_fixed=36,
   vm_save_sp=37,
   vm_restore_sp=38,
   vm_entry=39,
   vm_exit_8=40,
   vm_exit_16=41,
   vm_exit_24=42,
   vm_entry_close=43,
   vm_catch_8=44,
   vm_catch_16=45,
   vm_throw=46,
   vm_catch_close=47,
   vm_special_bind=48,
   vm_symbol_value=49,
   vm_symbol_value_set=50,
   vm_unbind=51,
   vm_progv=52,
   vm_fdefinition=53,
   vm_nil=54,
   vm_eq=55,
   vm_pop=56,
   vm_push=57,
   vm_long=58 };

#endif /*guard */
