#ifndef virtualMachine_H
#define virtualMachine_H

enum vm_codes {
   vm_ref=0,
   vm_const=1,
   vm_closure=2,
   vm_call=3,
   vm_call_receive_one=4,
   vm_call_receive_fixed=5,
   vm_bind=6,
   vm_set=7,
   vm_make_cell=8,
   vm_cell_ref=9,
   vm_cell_set=10,
   vm_make_closure=11,
   vm_make_uninitialized_closure=12,
   vm_initialize_closure=13,
   vm_return=14,
   vm_bind_required_args=15,
   vm_bind_optional_args=16,
   vm_listify_rest_args=17,
   vm_parse_key_args=18,
   vm_jump=19,
   vm_jump_if=20,
   vm_jump_if_supplied=21,
   vm_check_arg_count_LE_=22,
   vm_check_arg_count_GE_=23,
   vm_check_arg_count_EQ_=24,
   vm_push_values=25,
   vm_append_values=26,
   vm_pop_values=27,
   vm_mv_call=28,
   vm_mv_call_receive_one=29,
   vm_mv_call_receive_fixed=30,
   vm_entry=31,
   vm_exit=32,
   vm_entry_close=33,
   vm_catch=34,
   vm_throw=35,
   vm_catch_close=36,
   vm_special_bind=37,
   vm_symbol_value=38,
   vm_symbol_value_set=39,
   vm_unbind=40,
   vm_progv=41,
   vm_fdefinition=42,
   vm_nil=43,
   vm_eq=44 };

#endif /* guard */
