def build(bld):
    for name in [
            'adapter',
            'class_rep',
            'open',
            'class_registry',
            'link_compatibility',
            'scope',
            'inheritance',
            'clbind',
            'clbindPackage',
            'class',
            'derivable_class']:
        bld._source_files.append(bld.path.find_node(name+'.cc'))

        
