import os, logging

def subdirectories():
    dir = os.listdir("./extensions")
    print("subdirectories dir = %s" % dir)
    subdirs = []
    for x in dir:
        if os.path.isdir("./extensions/%s"%x):
            subdirs.append(x)
    print("extensions subdirs = %s" % subdirs)
    return subdirs

def build_extension(bld):
    print("recurse into seqan-clasp")
    bld.recurse("seqan-clasp")
    for subdir in subdirectories():
        print("recurse into %s" % subdir)
        bld.recurse(subdir,name="build_extension")

def grovel(bld):
    for subdir in subdirectories():
        print("recurse into %s" % subdir)
        bld.recurse(subdir,name="grovel")

def configure(cfg):
    subdirs = subdirectories()
    cfg.extensions_names = cfg.extensions_names + subdirs
    print("cfg.extensions_names = %s" % cfg.extensions_names)
    for subdir in subdirectories():
        print("recurse into %s" % subdir)
        cfg.recurse(subdir,name="configure")
    print("After recurse cfg.extensions_names = %s" % cfg.extensions_names)

def update_dependencies(cfg):
    print("In extensions update_dependencies - about to recurse into: %s" % (" ".join(subdirectories())))
    for subdir in subdirectories():
        print("recurse into %s" % subdir)
        cfg.recurse(subdir,name="update_dependencies")
    
def options(bld):
    for subdir in subdirectories():
        print("recurse into %s" % subdir)
        bld.recurse(subdir,name="options")

def build(bld):
    for subdir in subdirectories():
        print("recurse into %s" % subdir)
        bld.recurse(subdir,name="build")

def build3(bld):
    for subdir in subdirectories():
        print("recurse into %s" % subdir)
        bld.recurse(subdir,name="build3")
    
def build4(bld):
    for subdir in subdirectories():
        print("recurse into %s" % subdir)
        bld.recurse(subdir,name="build4")

def analyze_clasp(bld):
    for subdir in subdirectories():
        print("recurse into %s" % subdir)
        bld.recurse(subdir,name="analyze_clasp")
