
    "clang++" -x c++ -O0 -g -O1 -Wframe-larger-than=16 -Wlarger-than=4 -O0 -fno-inline -Wall -g -DDEBUG_ASSERTS -DEXPAT -DUSEBOOSTPYTHON -D_ADDRESS_MODEL_64 -D_DEBUG -D_DEBUG_BUILD -D_GNU_SOURCE -D_TARGET_OS_DARWIN -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I"../../build/cando.app/Contents/Resources/externals/gmp-5.0.5" -I"../../src" -I"../../src/core/bin/clang-darwin-4.2.1/debug" -I"../../src/llvmo" -I"../../src/llvmo/bin/clang-darwin-4.2.1/debug" -I"/Library/Frameworks/EPD64.framework/Versions/7.2/include/python2.7" -I"/Users/meister/Development/cando/brcl/build/cando.app/Contents/Resources/externals/release/include" -I"/Users/meister/Development/cando/brcl/build/llvm-dbg/include" -c -o "../../src/llvmo/bin/clang-darwin-4.2.1/debug/debugInfoExpose.o" "../../src/llvmo/debugInfoExpose.cc"


    "clang++" -x c++ -O0 -g -O1 -Wframe-larger-than=16 -Wlarger-than=4 -O0 -fno-inline -Wall -g -DDEBUG_ASSERTS -DEXPAT -DUSEBOOSTPYTHON -D_ADDRESS_MODEL_64 -D_DEBUG -D_DEBUG_BUILD -D_GNU_SOURCE -D_TARGET_OS_DARWIN -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I"../../build/cando.app/Contents/Resources/externals/gmp-5.0.5" -I"../../src" -I"../../src/core/bin/clang-darwin-4.2.1/debug" -I"../../src/llvmo" -I"../../src/llvmo/bin/clang-darwin-4.2.1/debug" -I"/Library/Frameworks/EPD64.framework/Versions/7.2/include/python2.7" -I"/Users/meister/Development/cando/brcl/build/cando.app/Contents/Resources/externals/release/include" -I"/Users/meister/Development/cando/brcl/build/llvm-dbg/include" -c -o "../../src/llvmo/bin/clang-darwin-4.2.1/debug/debugLoc.o" "../../src/llvmo/debugLoc.cc"

#clang-darwin.compile.c++ ../../src/llvmo/bin/clang-darwin-4.2.1/debug/llvmoDwarf.o

    "clang++" -x c++ -O0 -g -O1 -Wframe-larger-than=16 -Wlarger-than=4 -O0 -fno-inline -Wall -g -DDEBUG_ASSERTS -DEXPAT -DUSEBOOSTPYTHON -D_ADDRESS_MODEL_64 -D_DEBUG -D_DEBUG_BUILD -D_GNU_SOURCE -D_TARGET_OS_DARWIN -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I"../../build/cando.app/Contents/Resources/externals/gmp-5.0.5" -I"../../src" -I"../../src/core/bin/clang-darwin-4.2.1/debug" -I"../../src/llvmo" -I"../../src/llvmo/bin/clang-darwin-4.2.1/debug" -I"/Library/Frameworks/EPD64.framework/Versions/7.2/include/python2.7" -I"/Users/meister/Development/cando/brcl/build/cando.app/Contents/Resources/externals/release/include" -I"/Users/meister/Development/cando/brcl/build/llvm-dbg/include" -c -o "../../src/llvmo/bin/clang-darwin-4.2.1/debug/llvmoDwarf.o" "../../src/llvmo/llvmoDwarf.cc"

#clang-darwin.compile.c++ ../../src/llvmo/bin/clang-darwin-4.2.1/debug/intrinsics.o

    "clang++" -x c++ -O0 -g -O1 -Wframe-larger-than=16 -Wlarger-than=4 -O0 -fno-inline -Wall -g -DDEBUG_ASSERTS -DEXPAT -DUSEBOOSTPYTHON -D_ADDRESS_MODEL_64 -D_DEBUG -D_DEBUG_BUILD -D_GNU_SOURCE -D_TARGET_OS_DARWIN -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I"../../build/cando.app/Contents/Resources/externals/gmp-5.0.5" -I"../../src" -I"../../src/core/bin/clang-darwin-4.2.1/debug" -I"../../src/llvmo" -I"../../src/llvmo/bin/clang-darwin-4.2.1/debug" -I"/Library/Frameworks/EPD64.framework/Versions/7.2/include/python2.7" -I"/Users/meister/Development/cando/brcl/build/cando.app/Contents/Resources/externals/release/include" -I"/Users/meister/Development/cando/brcl/build/llvm-dbg/include" -c -o "../../src/llvmo/bin/clang-darwin-4.2.1/debug/intrinsics.o" "../../src/llvmo/intrinsics.cc"

# clang-darwin.compile.c++ ../../src/llvmo/bin/clang-darwin-4.2.1/debug/insertPoint.o

    "clang++" -x c++ -O0 -g -O1 -Wframe-larger-than=16 -Wlarger-than=4 -O0 -fno-inline -Wall -g -DDEBUG_ASSERTS -DEXPAT -DUSEBOOSTPYTHON -D_ADDRESS_MODEL_64 -D_DEBUG -D_DEBUG_BUILD -D_GNU_SOURCE -D_TARGET_OS_DARWIN -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I"../../build/cando.app/Contents/Resources/externals/gmp-5.0.5" -I"../../src" -I"../../src/core/bin/clang-darwin-4.2.1/debug" -I"../../src/llvmo" -I"../../src/llvmo/bin/clang-darwin-4.2.1/debug" -I"/Library/Frameworks/EPD64.framework/Versions/7.2/include/python2.7" -I"/Users/meister/Development/cando/brcl/build/cando.app/Contents/Resources/externals/release/include" -I"/Users/meister/Development/cando/brcl/build/llvm-dbg/include" -c -o "../../src/llvmo/bin/clang-darwin-4.2.1/debug/insertPoint.o" "../../src/llvmo/insertPoint.cc"

# clang-darwin.compile.c++ ../../src/llvmo/bin/clang-darwin-4.2.1/debug/irtests.o

    "clang++" -x c++ -O0 -g -O1 -Wframe-larger-than=16 -Wlarger-than=4 -O0 -fno-inline -Wall -g -DDEBUG_ASSERTS -DEXPAT -DUSEBOOSTPYTHON -D_ADDRESS_MODEL_64 -D_DEBUG -D_DEBUG_BUILD -D_GNU_SOURCE -D_TARGET_OS_DARWIN -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I"../../build/cando.app/Contents/Resources/externals/gmp-5.0.5" -I"../../src" -I"../../src/core/bin/clang-darwin-4.2.1/debug" -I"../../src/llvmo" -I"../../src/llvmo/bin/clang-darwin-4.2.1/debug" -I"/Library/Frameworks/EPD64.framework/Versions/7.2/include/python2.7" -I"/Users/meister/Development/cando/brcl/build/cando.app/Contents/Resources/externals/release/include" -I"/Users/meister/Development/cando/brcl/build/llvm-dbg/include" -c -o "../../src/llvmo/bin/clang-darwin-4.2.1/debug/irtests.o" "../../src/llvmo/irtests.cc"

# clang-darwin.compile.c++ ../../src/llvmo/bin/clang-darwin-4.2.1/debug/llvmoExpose.o

    "clang++" -x c++ -O0 -g -O1 -Wframe-larger-than=16 -Wlarger-than=4 -O0 -fno-inline -Wall -g -DDEBUG_ASSERTS -DEXPAT -DUSEBOOSTPYTHON -D_ADDRESS_MODEL_64 -D_DEBUG -D_DEBUG_BUILD -D_GNU_SOURCE -D_TARGET_OS_DARWIN -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I"../../build/cando.app/Contents/Resources/externals/gmp-5.0.5" -I"../../src" -I"../../src/core/bin/clang-darwin-4.2.1/debug" -I"../../src/llvmo" -I"../../src/llvmo/bin/clang-darwin-4.2.1/debug" -I"/Library/Frameworks/EPD64.framework/Versions/7.2/include/python2.7" -I"/Users/meister/Development/cando/brcl/build/cando.app/Contents/Resources/externals/release/include" -I"/Users/meister/Development/cando/brcl/build/llvm-dbg/include" -c -o "../../src/llvmo/bin/clang-darwin-4.2.1/debug/llvmoExpose.o" "../../src/llvmo/llvmoExpose.cc"


# clang-darwin.compile.c++ ../../src/llvmo/bin/clang-darwin-4.2.1/debug/llvmoPackage.o

    "clang++" -x c++ -O0 -g -O1 -Wframe-larger-than=16 -Wlarger-than=4 -O0 -fno-inline -Wall -g -DDEBUG_ASSERTS -DEXPAT -DUSEBOOSTPYTHON -D_ADDRESS_MODEL_64 -D_DEBUG -D_DEBUG_BUILD -D_GNU_SOURCE -D_TARGET_OS_DARWIN -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I"../../build/cando.app/Contents/Resources/externals/gmp-5.0.5" -I"../../src" -I"../../src/core/bin/clang-darwin-4.2.1/debug" -I"../../src/llvmo" -I"../../src/llvmo/bin/clang-darwin-4.2.1/debug" -I"/Library/Frameworks/EPD64.framework/Versions/7.2/include/python2.7" -I"/Users/meister/Development/cando/brcl/build/cando.app/Contents/Resources/externals/release/include" -I"/Users/meister/Development/cando/brcl/build/llvm-dbg/include" -c -o "../../src/llvmo/bin/clang-darwin-4.2.1/debug/llvmoPackage.o" "../../src/llvmo/llvmoPackage.cc"

# clang-darwin.link.dll ../../src/llvmo/bin/clang-darwin-4.2.1/debug/libllvmo_dbg.dylib

    "clang++" -dynamiclib -export-dynamic -install_name @executable-path/../Resources/lib/libllvmo_dbg.dylib -dynamiclib -export-dynamic -install_name @executable-path/../Resources/lib/libllvmo_dbg.dylib -L"/Library/Frameworks/EPD64.framework/Versions/7.2/lib" -L"/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/config" -L"/Users/meister/Development/cando/brcl/build/cando.app/Contents/Resources/externals/debug/lib" -L"/Users/meister/Development/cando/brcl/build/cando.app/Contents/Resources/externals/release/lib" -o "../../src/llvmo/bin/clang-darwin-4.2.1/debug/libllvmo_dbg.dylib" -single_module  "../../src/llvmo/bin/clang-darwin-4.2.1/debug/debugInfoExpose.o" "../../src/llvmo/bin/clang-darwin-4.2.1/debug/debugLoc.o" "../../src/llvmo/bin/clang-darwin-4.2.1/debug/llvmoDwarf.o" "../../src/llvmo/bin/clang-darwin-4.2.1/debug/intrinsics.o" "../../src/llvmo/bin/clang-darwin-4.2.1/debug/insertPoint.o" "../../src/llvmo/bin/clang-darwin-4.2.1/debug/irtests.o" "../../src/llvmo/bin/clang-darwin-4.2.1/debug/llvmoExpose.o" "../../src/llvmo/bin/clang-darwin-4.2.1/debug/llvmoPackage.o" "/Users/meister/Development/cando/brcl/build/cando.app/Contents/Resources/lib/libcore_dbg.dylib"   -lpython2.7 -lLLVM-3.3svn -lmps-debug -lgmpxx -lgmp -lncurses -lreadline -lz -lexpat -lboost_python -lboost_iostreams -lboost_system -lboost_program_options -lboost_serialization -lboost_date_time -lboost_thread -lboost_regex -lboost_filesystem  -g

