(k:sources :libclasp
           #~"debugInfoExpose.cc"
           #~"debugLoc.cc"
           #~"llvmoDwarf.cc"
           #~"link_intrinsics.cc"
           #~"builtins.cc"
           #~"intrinsics.cc"
           #~"insertPoint.cc"
           #~"irtests.cc"
           #~"llvmoExpose.cc"
           #~"code.cc"
           #~"llvmoPackage.cc"
           #~"trampoline_arena.cc"
           #~"trampolineWork.cc"
           #~"runtimeJit.cc"
           #~"clbindLlvmExpose.cc")
