def build(bld):
    bld._intrinsics = bld.path.find_node('intrinsics.cc')
    for name in [
            'debugInfoExpose',
            'debugLoc',
            'llvmoDwarf',
            'link_intrinsics',
            'intrinsics',
            'insertPoint',
            'irtests',
            'llvmoExpose',
            'llvmoPackage',
            'clbindLlvmExpose']:
        bld.clasp_source_files.append(bld.path.find_node(name+'.cc'))

        
