def build(bld):
    for name in [
            'debugInfoExpose',
            'debugLoc',
            'llvmoDwarf',
            'link_intrinsics',
            'intrinsics',
            'insertPoint',
            'irtests',
            'llvmoExpose',
            'llvmoPackage',
            'clbindLlvmExpose']:
        bld._source_files.append(bld.path.find_node(name+'.cc'))

        
