def build(bld):
    full_name = 'intrinsics.cc'
    node = bld.path.find_node(full_name)
    assert node != None, "Could not find %s/%s" % ( bld.path.abspath(), full_name )
    bld._intrinsics = node
    for name in [
            'debugInfoExpose',
            'debugLoc',
            'llvmoDwarf',
            'link_intrinsics',
            'builtins',
            'fastgf',
            'intrinsics',
            'insertPoint',
            'irtests',
            'llvmoExpose',
            'llvmoPackage',
            'clbindLlvmExpose']:
        full_name = name+'.cc'
        node = bld.path.find_node(full_name)
        assert node != None, "Could not find %s/%s" % ( bld.path.abspath(), full_name )
        bld.clasp_source_files.append(node)

        
