import os

def subdirectories():
    dir = os.listdir("./plugins")
    print("subdirectories dir = %s" % dir)
    subdirs = []
    for x in dir:
        if os.path.isdir("./plugins/%s"%x):
            subdirs.append(x)
    print("plugins subdirs = %s" % subdirs)
    return subdirs


def configure(cfg):
    subdirs = subdirectories()
    cfg.plugins_names = cfg.plugins_names + subdirs
    print("cfg.plugins_names = %s" % cfg.plugins_names)
    subdirs_str = " ".join(subdirs)
    print("About to recurse into %s" % subdirs_str)
    cfg.recurse(subdirs_str)
    print("After recurse cfg.plugins_names = %s" % cfg.plugins_names)

def build(bld):
    bld.recurse(" ".join(subdirectories()))

