;;; might work
;;;  MACROLET.36

;;; READ-SYMBOL.19
;;; ARRAY-T.3.1 
;;; THE.6
;;; THE.22
;;; MISC.132
;;; fails sometimes
;;; FORMAT.E.26

:NIL-VECTORS-ARE-STRINGS
:ALLOW-NIL-ARRAYS
:MAKE-CONDITION-WITH-COMPOUND-NAME
:NO-FLOATING-POINT-UNDERFLOW-BY-DEFAULT

PRINT.LONG-FLOAT.RANDOM

;;; These aren't true failures. They only happen because we use LOAD.
LOAD-PATHNAME.1
LOAD-TRUENAME.1

#-bytecode PEEK-CHAR.ERROR.1
PRINT.SYMBOL.RANDOM.3
PRINT.SYMBOL.RANDOM.4

;;; Clasp extends graphic-char-p to include space-like characters
FORMAT.C.2A
FORMATTER.C.2A

;;; ansi-test assumes that SYNONYM-STREAM doesn't act like FILE-STREAM
FILE-LENGTH.ERROR.3

;;; FIND-ALL-SYMBOLS.1
FUNCALL.ERROR.3
LOOP.1.39
LOOP.1.40
LOOP.1.41
LOOP.1.42
LOOP.1.43
DEFGENERIC.ERROR.20
DEFGENERIC.ERROR.21
CALL-NEXT-METHOD.ERROR.1
CALL-NEXT-METHOD.ERROR.2
DEFMETHOD.ERROR.14
DEFMETHOD.ERROR.15
UPGRADED-ARRAY-ELEMENT-TYPE.8
TYPE-OF.1
TYPE-OF.4
COMPILE-FILE.2
DEFCLASS.FORWARD-REF.3
#-bytecode MAKE-LOAD-FORM.ORDER.3
#-bytecode MAKE-LOAD-FORM.ORDER.4
#-bytecode MAKE-LOAD-FORM.ORDER.5
#-bytecode MAKE-LOAD-FORM.ORDER.6
#-bytecode MAKE-LOAD-FORM.ORDER.7
#-bytecode MAKE-LOAD-FORM.ORDER.8 
#-bytecode MAKE-LOAD-FORM.ORDER.9
#-bytecode MAKE-LOAD-FORM.ORDER.10
#-bytecode MAKE-LOAD-FORM.ORDER.11
#-bytecode MAKE-LOAD-FORM.ORDER.12
#-bytecode MAKE-LOAD-FORM.ORDER.13
#-bytecode MAKE-LOAD-FORM.ORDER.14
#-bytecode BUTLAST.FOLD.1
#-bytecode BUTLAST.FOLD.2
#-bytecode BUTLAST.FOLD.3
DEFSTRUCT.ERROR.3
DEFSTRUCT.ERROR.4
FORMAT.E.26

DEFINE-METHOD-COMBINATION-LONG.05.2
DEFINE-METHOD-COMBINATION-LONG.06.2
DEFINE-METHOD-COMBINATION-LONG.11.1
DEFINE-METHOD-COMBINATION-LONG.11.2
DEFINE-METHOD-COMBINATION-LONG.11.3
DEFINE-METHOD-COMBINATION-LONG.11.4