;;; might work
;;;  MACROLET.36

;;; READ-SYMBOL.19
;;; ARRAY-T.3.1 
;;; THE.6
;;; THE.22
;;; MISC.132
;;; fails sometimes
;;; FORMAT.E.26

:NIL-VECTORS-ARE-STRINGS
:ALLOW-NIL-ARRAYS
:MAKE-CONDITION-WITH-COMPOUND-NAME
:NO-FLOATING-POINT-UNDERFLOW-BY-DEFAULT

;;; These aren't true failures. They only happen because we use LOAD.
LOAD-PATHNAME.1
LOAD-TRUENAME.1

PRINT.SYMBOL.RANDOM.3
PRINT.SYMBOL.RANDOM.4
PRINT.DOUBLE-FLOAT.RANDOM
PRINT.LONG-FLOAT.RANDOM

;;; Clasp extends graphic-char-p to include space-like characters
FORMAT.C.2A
FORMATTER.C.2A

;;; these no longer crash, but fail
EXP.ERROR.4
EXP.ERROR.5
EXP.ERROR.6
EXP.ERROR.7
EXP.ERROR.8
EXP.ERROR.9
EXP.ERROR.10
EXP.ERROR.11
EXPT.ERROR.6
EXPT.ERROR.4
EXPT.ERROR.5
EXPT.ERROR.7
EXPT.ERROR.8
EXPT.ERROR.9 
EXPT.ERROR.10
EXPT.ERROR.11
;;; FIND-ALL-SYMBOLS.1
FUNCALL.ERROR.3
ATAN.IEEE.2 
LOOP.1.39
LOOP.1.40
LOOP.1.41
LOOP.1.42
LOOP.1.43
DEFGENERIC.ERROR.20
DEFGENERIC.ERROR.21
CALL-NEXT-METHOD.ERROR.1
CALL-NEXT-METHOD.ERROR.2
DEFMETHOD.ERROR.14
DEFMETHOD.ERROR.15
UPGRADED-ARRAY-ELEMENT-TYPE.8
ATAN.ERROR.5
MAP.ERROR.11
TYPE-OF.1
TYPE-OF.4
FORMAT.LOGICAL-BLOCK.23
COMPILE-FILE.2
DEFCLASS.FORWARD-REF.3

DEFSTRUCT.ERROR.3
DEFSTRUCT.ERROR.4
ALL-EXPORTED-CL-CLASS-NAMES-ARE-VALID
MAKE-TWO-WAY-STREAM.13
FORMAT.E.6
FORMAT.E.26

DEFINE-METHOD-COMBINATION-LONG.05.2
DEFINE-METHOD-COMBINATION-LONG.06.2
DEFINE-METHOD-COMBINATION-LONG.11.1
DEFINE-METHOD-COMBINATION-LONG.11.2
DEFINE-METHOD-COMBINATION-LONG.11.3
DEFINE-METHOD-COMBINATION-LONG.11.4