#! /bin/bash
llvm-link -o=_image_linked.bc \
    /Users/meister/Development/cando/brcl/src/llvmo/intrinsics.bc \
    /Users/meister/Development/cando/brcl/src/lisp/kernel/_image.bc \
    lsp/foundation.bc  \
    lsp/export.bc \
    lsp/defmacro.bc \
    lsp/helpfile.bc \
    lsp/evalmacros.bc \
    lsp/testing.bc \
    lsp/logging.bc \
    lsp/makearray.bc \
    cmp/cmpsetup.bc \
    cmp/cmpglobals.bc \
    cmp/cmpvar.bc \
    cmp/cmpintrinsics.bc \
    cmp/cmpir.bc \
    cmp/cmpeh.bc \
    cmp/debuginfo.bc \
    cmp/lambdalist.bc \
    cmp/cmpvars.bc \
    cmp/cmpquote.bc \
    cmp/compiler.bc \
    cmp/compilefile.bc \
    cmp/cmpbundle.bc \
    cmp/cmpwalk.bc \
    lsp/setf.bc \
    lsp/listlib.bc \
    lsp/mislib.bc \
    cmp/cmprepl.bc \
    lsp/predlib.bc \
    lsp/sharpmacros.bc \
    lsp/cmuutil.bc \
    lsp/seqmacros.bc \
    lsp/seqlib.bc \
    lsp/seq.bc \
    lsp/assert.bc \
    lsp/defstruct.bc \
    lsp/iolib.bc \
    lsp/module.bc \
    lsp/trace.bc \
    lsp/loop2.bc \
    lsp/packlib.bc \
    lsp/defpackage.bc \
    lsp/format.bc \
    clos/package.bc \
    clos/hierarchy.bc \
    clos/cpl.bc \
    clos/std-slot-value.bc \
    clos/slot.bc \
    clos/boot.bc \
    clos/kernel.bc \
    clos/method.bc \
    clos/combin.bc \
    clos/std-accessors.bc \
    clos/defclass.bc \
    clos/slotvalue.bc \
    clos/standard.bc \
    clos/builtin.bc \
    clos/change.bc \
    clos/stdmethod.bc \
    clos/generic.bc \
    clos/fixup.bc \
    clos/extraclasses.bc \
    clos/conditions.bc \
    clos/print.bc \
    clos/streams.bc \
    lsp/pprint.bc \
    lsp/describe.bc \
    clos/inspect.bc \
    lsp/ffi.bc \
    lsp/top.bc 
opt -internalize -inline _image_linked.bc -o=_image_opt.bc
llc -filetype=obj _image_opt.bc
ld -v _image_opt.o -macosx_version_min 10.7 -flat_namespace -undefined warning -bundle -o /Users/meister/Development/cando/brcl/src/lisp/kernel/_image_opt.bundle
