(format t "Building cleavir clasp full version - loading compile-cclasp.lisp~%")
(defpackage #:cclasp-build
  (:use #:common-lisp #:core))
(in-package :cclasp-build)
(format t "Loading cleavir-system.lsp~%")
(core::add-cleavir-to-*system-files*)
(setq *features* (list* :clos :cclasp (remove :bclasp *features*)))
(setq core:*target-backend* (core::default-target-backend))
(core:clean-system nil :no-prompt t :stage "cclasp")
(core:load-system :bclasp :cclasp) ;; :pre-inline)
(core:compile-system :init :cclasp :recompile nil :reload nil)
(core:quit)
