#! /bin/env python.exe

import sys
from mbbCore import *

print "Reading from file: ",sys.argv[1]

a = Aggregate()
moeReadAggregateFromFileName(a,sys.argv[1])

seq = []
l = Loop()
l.loopTopAggregateGoal(a,RESIDUES)
while (l.advanceLoopAndProcess()):
    res = l.getResidue()
    resName = "%s%d"%(res.getName(),len(seq)+1)
    seq.append(resName)
    print "RESIdue %s"%resName
    la = Loop()
    la.loopTopResidueGoal(res,ATOMS)
    while (la.advanceLoopAndProcess()):
	atom = la.getAtom()
	print " Atom %s TYPE=%s CHARGE=%f END"%(atom.getName(),atom.getMoeType(),atom.getCharge())
    print "END"
