def build(bld):
    loc = bld.path.relpath()
    def full_name(name):
        return loc + '/' + name

    for name in [
            'serveEvent',
            'serveEventPackage'
    ]:
        bld(features='cxx', source=name+'.cc', target=full_name(name))

        
