
sa subAll sb subBundle sad:
	make -C ./init $@
	make -C ./db $@
	make -C ./patterns $@
	make -C ./charges $@
	make -C ./tools $@
	make -C ./hits $@
#	make -C ./gbw $@
#	make -C ./viewer $@

subMeta sm:
	echo Nothing

subClean sc:
	echo Do nothing
