/*
    File: globals.cc
*/

/*
Copyright (c) 2014, Christian E. Schafmeister
 
CLASP is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.
 
See directory 'clasp/licenses' for full details.
 
The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
/* -^- */
#include <clasp/core/foundation.h>
#include <clasp/core/object.h>
#include <clasp/core/core_globals.h>

/*! Move all global/static variable definitions into this file so that we can control them
 */

namespace core {

uint __nextPredefinedSymbolIndex = 0;
};

#pragma GCC visibility push(default)

extern "C" {
/*! This stores a pointer to the smart_ptr to the run-time value vector.
      This is linked to by LLVM Modules generated by COMPILE.
      We use a pointer to the smart_ptr because we don't want
      to have to maintain this as a garbage collection root.
    */
core::LoadTimeValues_O *globalTaggedRunTimeValues ATTR_WEAK = NULL;
};
#pragma GCC visibility pop

extern "C" {
/*
 * Store the global lisp object
 */
core::Lisp_sp _lisp;

bool debug_mps = true;
};
