#! /usr/bin/env python

import sys
import glob
import os.path

extra = sys.argv[1]

print "mbbCore ",
objectFiles = glob.glob("./*.o")
for rp in objectFiles:
    a = os.path.realpath(rp)
    print a,
print extra
