    "/usr/bin/clang" -v -x c++ -O3 -gdwarf-4 -Warray-bounds -Wgnu-array-member-paren-init -Wno-deprecated-register -Wno-unused-local-typedef -Wno-unused-variable -fvisibility=default -mmacosx-version-min=10.7 -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.0 -std=c++11 -stdlib=libc++ -O3 -O3 -gdwarf-4 -O3 -Wno-inline -DCLASP_GIT_COMMIT=\"b628ecd30776f0b38bb6ba8e35877b23612b062d\" -DCLASP_VERSION=\"0.1\" -DCLBIND_DYNAMIC_LINK -DDEBUG_CL_SYMBOLS -DEXPAT -DINCLUDED_FROM_CLASP -DINHERITED_FROM_SRC -DNDEBUG -DREADLINE -DUSE_BOEHM -DUSE_CLASP_DYNAMIC_CAST -DUSE_STATIC_ANALYZER_GLOBAL_SYMBOLS -D_ADDRESS_MODEL_64 -D_RELEASE_BUILD -D_TARGET_OS_DARWIN -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I"../../src" -I"../../src/core" -I"../../src/core/bin/boehm/clang-darwin-4.2.1/release/link-static" -I"/Users/meister/.local/externals-clasp/common/include" -I"/Users/meister/.local/externals-clasp/release/include" -c -o "../../src/core/bin/boehm/clang-darwin-4.2.1/release/link-static/write_ugly.o" "../../src/core/write_ugly.cc"


    "/Users/meister/.local/externals-clasp/release/bin/clang++" -v -x c++ -O3 -gdwarf-4 -Warray-bounds -Wgnu-array-member-paren-init -Wno-deprecated-register -Wno-unused-local-typedef -Wno-unused-variable -fvisibility=default -mmacosx-version-min=10.7 -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.0 -std=c++11 -stdlib=libc++ -O3 -O3 -gdwarf-4 -O3 -Wno-inline -DCLASP_GIT_COMMIT=\"b628ecd30776f0b38bb6ba8e35877b23612b062d\" -DCLASP_VERSION=\"0.1\" -DCLBIND_DYNAMIC_LINK -DDEBUG_CL_SYMBOLS -DEXPAT -DINCLUDED_FROM_CLASP -DINHERITED_FROM_SRC -DNDEBUG -DREADLINE -DUSE_BOEHM -DUSE_CLASP_DYNAMIC_CAST -DUSE_STATIC_ANALYZER_GLOBAL_SYMBOLS -D_ADDRESS_MODEL_64 -D_RELEASE_BUILD -D_TARGET_OS_DARWIN -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS \
-I"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include" \
-I"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks" \
-I"../../src" -I"../../src/core" -I"../../src/core/bin/boehm/clang-darwin-4.2.1/release/link-static" -I"/Users/meister/.local/externals-clasp/common/include" -I"/Users/meister/.local/externals-clasp/release/include" -c -o "../../src/core/bin/boehm/clang-darwin-4.2.1/release/link-static/write_ugly.o" "../../src/core/write_ugly.cc"




/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include
