#! /bin/bash
#
# In the clasp toplevel directory use...
#   make -f apptainer/makefile
#

rm -rf build-apptainer/*
tar --exclude-vcs -cvf systems.tar -C $HOME ./common-lisp ./work/spiros/data ./work/data ~/common-lisp/amber-protein/products/
apptainer build -F --bind $PWD:/mnt cando.sif apptainer/cando.def
