

move-files:
	git mv ../../src/asttooling/*.h asttooling/
	git mv ../../src/cffi/*.h cffi/
	git mv ../../src/core/*.h core/
	git mv ../../src/gctools/*.h gctools/
	git mv ../../src/llvmo/*.h llvmo/
	git mv ../../src/main/*.h main/
	git mv ../../src/mpip/*.h mpip/
	git mv ../../src/serveEvent/*.h serveEvent/
	git mv ../../src/sockets/*.h sockets/
