

sa subAll:
	make docs

sb subBundle:
	echo Do nothin

dox:
	doxygen Doxyfile

manual:
	make -C $(CANDO_HOME)/src/core userDocs.pdf
	install -c $(CANDO_HOME)/src/core/userDocs.pdf $(OS_BUILDTOP)

subClassTree sct:
	@echo do nothing

subParsers:
	@echo No parsers, do nothing
