#! /usr/bin/env python

import json
import re
import os
import sys

buildDumpFileName = sys.argv[1]
outputFileName = sys.argv[2]
#compilation_re = re.compile(".*clang\+\+[^-]*-c")
compilation_re = re.compile("\s*\"clang[^\-]*-x")

database = []

fin = open(buildDumpFileName,"r")
ln = 0
for l in fin.readlines():
    ln += 1
    line = l.strip().rstrip()
#    print( "READ: %s" % line)
# Check for new way of defining LISP classes
    match = compilation_re.match(l)
    if ( match != None ):
        lastPart = line.split(" ")[-1]
        relFileName = lastPart.strip("\"")
        absPath = os.path.abspath(relFileName)
        dir = os.path.dirname(absPath)
        fileName = os.path.basename(absPath)
        entry = { "command" : line, "file" : fileName, "directory": dir }
        database.append(entry)
        print("processing %s/%s" % (dir, fileName))


fin.close()            

fout = open(outputFileName,"w")
json.dump(database,fout,indent=2)
fout.close()
