#! /bin/bash
sif_file=$1
shift
#echo $*
sbcl --noinform --lose-on-corruption --dynamic-space-size 4096 --load $CLASP_HOME/src/scraper/scraper.lisp --eval "(progn (cscrape:generate-one-sif \"$*\" #P\"$sif_file\")(quit))"

