#! /bin/bash
# arguments:   pid [output-file [time] [sample-speed-hz] [stack-frames]

PID=$1
OUTFILE=${2:-"/tmp/out.user_stacks"}
TIME=${3:-60s}
RATE=${4:-97}
FRAMES=${5:-1000}
sudo dtrace -p $PID -x ustackframes=${FRAMES} -n  "profile-$RATE /pid == $PID && arg1 / { @[ustack()] = count(); } tick-$TIME { exit(0); }" -o $OUTFILE
# PRUNE_OUTFILE=${OUTFILE%.prune_stacks}
# ./prune-trace.lisp $OUTFILE $PRUNE_OUTFILE
