#! /bin/bash
PID=$1
TIME=${2:-60s}
RATE=${3:-97}
FRAMES=${4:-6000}
## in case there is no symbols file
#sudo rm -f /tmp/out-$1.user_stacks && sudo dtrace -p $PID -x ustackframes=${FRAMES} -n  "profile-$RATE /pid == $PID && arg1 / { @[ustack()] = count(); } tick-$TIME { exit(0); }" -o /tmp/out-$1.user_stacks
#if [ -f /tmp/clasp-symbols-$1 ]; then
#   ./symbolicate.lisp -i /tmp/out-$1.user_stacks -o /tmp/out-symbol-$1.user_stacks -s /tmp/clasp-symbols-$1
#else
#   cp /tmp/out-$1.user_stacks /tmp/out-symbol-$1.user_stacks
#fi
if [[ "$OSTYPE" == "darwin"* ]]; then

./do-dtrace $PID $TIME $RATE $FRAMES

elif [[ "$OSTYPE" == "linux-gnu" ]]; then

./do-perf $PID $TIME $RATE $FRAMES
./perf2dtrace -i /tmp/out-$1.perf -o /tmp/out-$1.raw.stacks

#if [ -f /tmp/clasp-symbols-$PID ]; then
#   ./symbolicate.lisp -i /tmp/out-$PID.raw.stacks -o /tmp/out-$PID.sym.stacks -s /tmp/clasp-symbols-$PID
#else
   cp /tmp/out-$PID.raw.stacks /tmp/out-$PID.sym.stacks
#fi
./cleanup-stacks -i /tmp/out-$PID.sym.stacks -o /tmp/out-$PID.stacks

fi

./collapse -i /tmp/out-$1.stacks -o /tmp/out-$1.folded -m 400

$FLAME_GRAPH_HOME/flamegraph.pl -color clasp /tmp/out-$1.folded >/tmp/out-$1.svg
echo /tmp/out-$1.svg
