#! /bin/bash
PID=$1
TIME=${2:-60s}
RATE=${3:-97}
FRAMES=${4:-10000}
## in case there is no symbols file
#sudo rm -f /tmp/out-$1.user_stacks && sudo dtrace -p $PID -x ustackframes=${FRAMES} -n  "profile-$RATE /pid == $PID && arg1 / { @[ustack()] = count(); } tick-$TIME { exit(0); }" -o /tmp/out-$1.user_stacks
#if [ -f /tmp/clasp-symbols-$1 ]; then
#   ./symbolicate.lisp -i /tmp/out-$1.user_stacks -o /tmp/out-symbol-$1.user_stacks -s /tmp/clasp-symbols-$1
#else
#   cp /tmp/out-$1.user_stacks /tmp/out-symbol-$1.user_stacks
#fi
./do-dtrace $PID $TIME $RATE $FRAMES
./collapse -i /tmp/out-$1.stacks -o /tmp/out-$1.folded -m 1000
$FLAME_GRAPH_HOME/flamegraph.pl /tmp/out-$1.folded >/tmp/out-$1.svg
echo /tmp/out-$1.svg
