(in-package #:clasp-tests)
(test test-standard-char-p-$ (standard-char-p #\$))

;;; CHAR= CHAR/= CHAR< CHAR> CHAR<= CHAR>= CHAR-LESSP CHAR-GREATERP CHAR-EQUAL CHAR-NOT-LESSP CHAR-NOT-GREATERP CHAR-NOT-EQUAL 
;;; Should signal an error of type program-error if at least one character is not supplied.

(TEST-EXPECT-ERROR TEST-CHAR-0 (CHAR=) :TYPE PROGRAM-ERROR)
(TEST-EXPECT-ERROR TEST-CHAR-1 (CHAR/=) :TYPE PROGRAM-ERROR)
(TEST-EXPECT-ERROR TEST-CHAR-2 (CHAR<) :TYPE PROGRAM-ERROR)
(TEST-EXPECT-ERROR TEST-CHAR-3 (CHAR>) :TYPE PROGRAM-ERROR)
(TEST-EXPECT-ERROR TEST-CHAR-4 (CHAR<=) :TYPE PROGRAM-ERROR)
(TEST-EXPECT-ERROR TEST-CHAR-5 (CHAR>=) :TYPE PROGRAM-ERROR)
(TEST-EXPECT-ERROR TEST-CHAR-6 (CHAR-LESSP) :TYPE PROGRAM-ERROR)
(TEST-EXPECT-ERROR TEST-CHAR-7 (CHAR-GREATERP) :TYPE PROGRAM-ERROR)
(TEST-EXPECT-ERROR TEST-CHAR-8 (CHAR-EQUAL) :TYPE PROGRAM-ERROR)
(TEST-EXPECT-ERROR TEST-CHAR-9 (CHAR-NOT-LESSP) :TYPE PROGRAM-ERROR)
(TEST-EXPECT-ERROR TEST-CHAR-10 (CHAR-NOT-GREATERP) :TYPE PROGRAM-ERROR)
(TEST-EXPECT-ERROR TEST-CHAR-11 (CHAR-NOT-EQUAL) :TYPE PROGRAM-ERROR)