(in-package #:clasp-tests)

(setq *expected-failures*
      '(ANSI-PUSHNEW.14A 
        LOOP-FIXNUM-1 LOOP-FINALLY-1 LOOP-FINALLY-2 LOOP-FINALLY-3 LOOP-FINALLY-4
        PRINT-READ-1
        TYPES-CLASSES-10
        HASH-TABLE-SIZE-WEAK-KEY
        #-cst BABEL-SIMPLE-STRINGS-1
        ;;; printer
        PRINT.ARRAY.RANDOM.1.TAKE.1
        PRINT.ARRAY.RANDOM.1.TAKE.2
        PRINT.VECTOR.RANDOM.1.TAKE.1
        PRINT.VECTOR.RANDOM.1.TAKE.2

        READ-SYMBOL.19
        READ-SUPPRESS.17
        CLHS-23.2.16
        
        ;;; unary operands and error checks
        MAX-2A
        MIN-2A
        NUMBER-COMPARISON-REAL-1A
        NUMBER-COMPARISON-REAL-2A
        NUMBER-COMPARISON-REAL-3A
        NUMBER-COMPARISON-REAL-4A
        NUMBER-COMPARISON-REAL-7A
        NUMBER-COMPARISON-REAL-8A
        NUMBER-COMPARISON-REAL-9A
        NUMBER-COMPARISON-REAL-10A
        NUMBER-COMPARISON-NUMBER-11A
        NUMBER-COMPARISON-NUMBER-12A
        NUMBER-COMPARISON-NUMBER-13A
        NUMBER-COMPARISON-NUMBER-14A
        TEST-CHAR-0A
        TEST-CHAR-1A
        TEST-CHAR-2A TEST-CHAR-3A TEST-CHAR-4A TEST-CHAR-5A
        TEST-CHAR-6A TEST-CHAR-7A TEST-CHAR-8A TEST-CHAR-9A
        TEST-CHAR-10A TEST-CHAR-11A
        READ-PRINT-CONSISTENCY-ARRAYS
        SBCL-CROSS-COMPILE-4 ;;;not important
        INCLUDE-LEVEL-2A INCLUDE-LEVEL-2B INCLUDE-LEVEL-3 ;;; a problem for sbcl x-compiling
        TEST-ISSUE-946 TEST-ISSUE-950 
        )
      )
