#! /usr/bin/env python -O

import sys,os
import mbb

scriptFileName = sys.argv[1]

prog = mbb.create_Script()
try:
    success = prog.compileScriptInFileName(scriptFileName)
    if ( success ):
        prog.run()
except UserWarning, e:
    print "%s"%e
