#! /usr/bin/env awk -f
BEGIN { depth = 0; }
/^{/ { depth = depth + 1; print $0; next;}
/^}/ { depth = depth - 1; print $0; next;}
//   { print $0; }

END {
    printf("PREMATURE TERMINATION!!!! - filled in by fixLog\n");
    while ( depth > 0 )
    {
	printf( "}\n" );
	depth = depth - 1;
    }
}